name: Create Archive
on: [push]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: pull latest and remove old file from repo
      env:
        GITHUB_TOKEN: ${{ secrets.RESOURCE_ZIPPER }}
      run: |
        git config --global user.name "AidanSkye"
        git config --global user.email "mccartyaidan2011@gmail.com"
        git config pull.rebase false
        git pull
        rm -f release.zip
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.RESOURCE_ZIPPER }}
      with:
        filename: 'release.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
    - name: push changes to remote
      env:
        GITHUB_TOKEN: ${{ secrets.RESOURCE_ZIPPER }}
      run: |
        git add -A
        git commit -m "new pack"
        git push --force